on:
    push:
        branches:
            - main

jobs:
    # https://github.com/marketplace/actions/contribute-list
    # .guthub/workflows/readme.md
    contrib-readme-job:
        runs-on: ubuntu-latest
        name: A job to automate contrib in readme
        permissions:
          contents: write
          pull-requests: write
        steps:
            - name: Contribute List
              uses: akhilmhdh/contributors-readme-action@v2.3.10
              with:
                  auto_detect_branch_protection: true
                  commit_message: "chore(contributor|workflow): contrib-readme-action has updated readme" # update as needed
                  committer_username: ipoetdev # update as needed for repo maintainer
                  committer_email: ipoetdev-github-no-reply@outlook.com # repo maintainer's email
                  pr_title_on_protected: "PR: chore(contributor|workflow): contrib-readme-action has updated readme"
                  columns_per_row: 6
                  use_username: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}